from .model_1 import MatchNet as model_1
from .model_2 import RelationNet as model_2
from .model_3 import RelationNet as model_3
from .model_4 import RelationNet as model_4
from .model_5 import RelationNet as model_5
from .model_6 import RelationNet as model_6
from .model_7 import RelationNet as model_7
from .model_8 import RelationNet as model_8
from .model_9 import RelationNet as model_9
from .model_10 import RelationNet as model_10